- url: https://jsonplaceholder.typicode.com/posts
  method: GET
  headers:
    - name: Content-Type
      value: application/json
    - name: X-Secret-Key
      value: secret
      env_secret: BITBUCKET_SECRET_TOKEN
  threads: 125
  requests: 3000
  duration: 30s